# Run with: ansible-playbook -i hosts magento.yml
---
- name: Install WebServer for Magento 
  hosts: all
  sudo: True

- name: Install mysql nginx, PHP-FPM, Varnish, memcached
  hosts: web

  roles:
    - nginx
    - mysql
    - php-fpm
    - varnish
    - memcache
