---
- name: Install memcached 
  apt: name={{ item }} state=present
  with_items:
    - memcached
  become: true
  become_method: sudo

- name: Start memcached
  service: name=memcached state=started enabled=yes
  become: true
  become_method: sudo