---
- name: Install Mysql package
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - mysql-server-5.5
   - mysql-client-5.5

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
   - "{{ mysql_host }}"
   - 127.0.0.1
   - ::1
   - localhost

- name: copy .my.cnf file with root password credentials
  template: src=root.my dest=/root/.my.cnf owner=root mode=0600
