---
- name: Fetch the repository packages from Percona
  raw: wget https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb

- name: Install the downloaded package with dpkg
  raw: sudo dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb

- name: Update apt
  raw: sudo apt-get update

- name: Install Mysql package
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - percona-server-server-5.7
   - percona-server-common-5.7
   - percona-server-client-5.7

- name: update mysql root password for all root accounts
  mysql_user: name=root host=localhost password=qwerty
  with_items:
   - "{{ mysql_host }}"
   - 127.0.0.1
   - ::1
   - localhost

- name: copy .my.cnf file with root password credentials
  template: src=root.my dest=/root/.my.cnf owner=root mode=0600
