---
- name: Fetch the repository packages from Percona
  raw: wget https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb

- name: Install the downloaded package with dpkg
  raw: sudo dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb

- name: Update apt
  raw: sudo apt-get update

- name: Install Mysql package
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - percona-server-server-5.7
   - percona-server-common-5.7
   - percona-server-client-5.7
   - python-mysqldb

  become: true
  become_method: sudo
